### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by wethecom** [angelleye/paypal-ipn-template#2]
june 30 2017 it will require https
?dose this mean my website is going to need a https adress or is it all handled in the postback protocols..(i have no idea where that is handled)?
https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1916&viewlocale=en_US

**Comment by angelleye** [comment]
I'm sorry for the delay responding.  Somehow I missed the notification for this message.

Your website will not need to run on https://.  You just need to make sure that when you POST data back to PayPal within an IPN script for verification that you're using https:// on their address.

I do need to make an adjustment to this solution so it will use HTTP 1.1 instead of 1.0 like it is now.  I'll be sure to make that adjustment before the required date.

**Comment by wethecom** [comment]
https://github.com/angelleye/paypal-ipn-template/blob/master/validate.php

so im guessing its just a change of 

 $header .= "POST /cgi-bin/webscr HTTP/1.0\r\n";  
to
 $header .= "POST /cgi-bin/webscr HTTP/1.1\r\n";  
in a few locations
